#!/bin/bash

takedown() {
    cd vagrant
    vagrant ssh -c "
export FACTOR_MACHINE_TYPE=$FACTOR_MACHINE_TYPE_LEVEL
export FACTOR_TSERVER_COUNT=$FACTOR_TSERVER_COUNT_LEVEL
export FACTOR_SHARD_REPLICATION=$FACTOR_SHARD_REPLICATION_LEVEL
export FACTOR_TRANSACTION_ISOLATION=$FACTOR_TRANSACTION_ISOLATION_LEVEL
export FACTOR_WORKLOAD_TYPE=$FACTOR_WORKLOAD_TYPE_LEVEL
export FACTOR_OPERATION_SIZE=$FACTOR_OPERATION_SIZE_LEVEL
./esle24-g1/vagrant/run.sh --skip-deploy --skip-test"
    cd ..
}

set -e

if [ "$#" -ne 6 ]; then
    echo "Usage: $0 <FACTOR_MACHINE_TYPE_LEVEL> <FACTOR_TSERVER_COUNT_LEVEL> <FACTOR_SHARD_REPLICATION_LEVEL> <FACTOR_TRANSACTION_ISOLATION_LEVEL> <FACTOR_WORKLOAD_TYPE_LEVEL> <FACTOR_OPERATION_SIZE_LEVEL>"
    exit 1
fi

export FACTOR_OPERATION_SIZE_LEVEL=$1
export FACTOR_WORKLOAD_TYPE_LEVEL=$2
export FACTOR_TSERVER_COUNT_LEVEL=$3
export FACTOR_TRANSACTION_ISOLATION_LEVEL=$4
export FACTOR_SHARD_REPLICATION_LEVEL=$5
export FACTOR_MACHINE_TYPE_LEVEL=$6

NEED_DEPLOY=true

DEPLOY_OPTS="--skip-deploy"
if [ "$NEED_DEPLOY" == "true" ]; then
    DEPLOY_OPTS=""
    takedown
fi

cd vagrant
vagrant ssh -c "
export FACTOR_MACHINE_TYPE=$FACTOR_MACHINE_TYPE_LEVEL
export FACTOR_TSERVER_COUNT=$FACTOR_TSERVER_COUNT_LEVEL
export FACTOR_SHARD_REPLICATION=$FACTOR_SHARD_REPLICATION_LEVEL
export FACTOR_TRANSACTION_ISOLATION=$FACTOR_TRANSACTION_ISOLATION_LEVEL
export FACTOR_WORKLOAD_TYPE=$FACTOR_WORKLOAD_TYPE_LEVEL
export FACTOR_OPERATION_SIZE=$FACTOR_OPERATION_SIZE_LEVEL
./esle24-g1/vagrant/run.sh $DEPLOY_OPTS"
cd ..
