- name: Deploy YugabyteDB Master
  hosts: masters
  become: yes
  vars_files:
    - "{{ playbook_dir }}/vars.yml"
  tasks:
    - name: Create directory for YugabyteDB data
      file:
        path: /mnt/yugabyte_data
        state: directory
        mode: '0755'

    - name: Start YugabyteDB Master with nohup
      shell: |
        nohup /opt/yugabyte/yugabyte-2024.1.3.0/bin/yb-master \
        --master_addresses {{ hostvars['yb-master1'].ansible_host_internal }}:7100,{{ hostvars['yb-master2'].ansible_host_internal }}:7100,{{ hostvars['yb-master3'].ansible_host_internal }}:7100 \
        --rpc_bind_addresses {{ ansible_host_internal }}:7100 \
        --fs_data_dirs "/mnt/yugabyte_data" \
        --placement_cloud gcp \
        --placement_region europe-central2 \
        --placement_zone europe-central2-a \
        --use_memory_defaults_optimized_for_ysql \
        --ysql_num_shards_per_tserver 1 \
        {{ yb_replication_factor_flag }} > /mnt/yugabyte_data/yb-master.log 2>&1 &
      args:
        executable: /bin/bash
      environment:
        PATH: "{{ ansible_env.PATH }}"
