---
- name: Install prerequisites and download YugabyteDB on Ubuntu
  hosts: targets
  become: yes
  tasks:
    # Ensure Python 3 is installed
    - name: Ensure Python 3 is installed
      apt:
        name: python3
        state: present

    # Ensure 'python-is-python3' is installed for Ubuntu 20.04 and later
    - name: Ensure 'python-is-python3' is installed
      apt:
        name: python-is-python3
        state: present
      when: ansible_distribution_version >= "20.04"

    # Ensure wget is installed
    - name: Ensure wget is installed
      apt:
        name: wget
        state: present

    # Ensure curl is installed
    - name: Ensure curl is installed
      apt:
        name: curl
        state: present

    # Create the directory for YugabyteDB
    - name: Create directory for YugabyteDB
      file:
        path: /opt/yugabyte
        state: directory
        mode: '0755'

    # Download YugabyteDB x86 package
    - name: Download YugabyteDB x86 package
      get_url:
        url: https://downloads.yugabyte.com/releases/2024.1.3.0/yugabyte-2024.1.3.0-b105-linux-x86_64.tar.gz
        dest: /tmp/yugabyte-2024.1.3.0-b105-linux-x86_64.tar.gz

    # Extract YugabyteDB package
    - name: Extract YugabyteDB package
      unarchive:
        src: /tmp/yugabyte-2024.1.3.0-b105-linux-x86_64.tar.gz
        dest: /opt/yugabyte
        remote_src: yes
        creates: /opt/yugabyte/yugabyte-2024.1.3.0

    # Run the post-install script
    - name: Run the post-install script
      command: /opt/yugabyte/yugabyte-2024.1.3.0/bin/post_install.sh
      args:
        chdir: /opt/yugabyte/yugabyte-2024.1.3.0
